apiVersion: v1
kind: Pod
metadata:
  name: jenkins-slave
spec:
  containers:
    - name: jenkins-slave-with-docker
      image: korekontrol/jnlp-slave-docker
      workingDir: /home/jenkins
      serviceAccountName: jenkins
      env:
        - name: DOCKER_HOST
          value: tcp://localhost:2375
    - name: dind-daemon
      image: docker:dind
      workingDir: /var/lib/docker
      serviceAccountName: jenkins
      securityContext:
        privileged: true
      volumeMounts:
        - name: docker-storage
          mountPath: /var/lib/docker
  volumes:
    - name: docker-storage
      emptyDir: {}
