apiVersion: v1
kind: Pod
metadata:
  name: jnlp
spec:
  containers:
    - name: jnlp
      image: ikenoxamos/jenkins-slave:latest
      workingDir: /home/jenkins
      serviceAccountName: jenkins
      env:
        - name: DOCKER_HOST
          value: tcp://localhost:2375
      resources:
        requests:
          memory: "500Mi"
          cpu: "0.3"
        limits:
          memory: "800Mi"
          cpu: "0.5"
    - name: dind-daemon
      image: docker:18-dind
      workingDir: /var/lib/docker
      serviceAccountName: jenkins
      securityContext:
        privileged: true
      volumeMounts:
        - name: docker-storage
          mountPath: /var/lib/docker
      resources:
        requests:
          memory: "300Mi"
          cpu: "0.3"
        limits:
          memory: "500Mi"
          cpu: "0.5"
  volumes:
    - name: docker-storage
      emptyDir: {}
