apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: project0-express-deployment
  labels:
    app: project0-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project0-express
  template:
    metadata:
      labels:
        app: project0-express
    spec:
      containers:
        - name: project0-express
          image: ikenoxamos/project0-express:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9001
---
apiVersion: v1
kind: Service
metadata:
  name: project0-express-service
spec:
  type: NodePort
  selector:
    app: project0-express
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 9001
      name: p0-express-port
