apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: project0-express-deployment
  labels:
    app: project0-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project0-express
  template:
    metadata:
      labels:
        app: project0-express
    spec:
      containers:
        - name: project0-express
          image: ikenoxamos/project0-express:latest
          readinessProbe:
            httpGet:
              path: /health
              port: 9001
          imagePullPolicy: Always
          ports:
            - containerPort: 9001
---
apiVersion: v1
kind: Service
metadata:
  name: project0-express-service
spec:
  type: NodePort
  selector:
    app: project0-express
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 9001
      name: p0-express-port
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: project0-express-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
        paths:
          - path: /project0-express(/|$)(.*)
            backend:
              serviceName: project0-express-service
              servicePort: p0-express-port
